export const ConstantControllerStatus = {
  SUCCESS: 'SUCCESS',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_DELETE_DATE_CONDITION: 'INVALID_DELETE_DATE_CONDITION',
  INVALID_UPDATE_DATE_CONDITION: 'INVALID_UPDATE_DATE_CONDITION',
  INVALID_OLD_PASSWORD_CONDITION: 'INVALID_OLD_PASSWORD_CONDITION',
};
